platform :android do
    desc "release android beta"
    lane :beta do
        increment_version_code(gradle_file_path: './android/app/build.gradle')
        gradle(task: 'clean', project_dir: './android')
        gradle(task: 'bundle', build_type: 'Release', project_dir: './android')
    end
end

lane :test do
end